version: '2'
services:
    jhipstersample1-app:
        image: jhipstersample1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersample1-mysql:3306/jhipstersample1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersample1-mysql:
        extends:
            file: mysql.yml
            service: jhipstersample1-mysql
